/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  stripeSessionId?: string;
  status?: "paid" | "ready_to_ship" | "shipped" | "cancelled";
  customerName?: string;
  customerEmail?: string;
  customerPhone?: string;
  shippingAddress?: {
    name?: string;
    line1?: string;
    line2?: string;
    city?: string;
    state?: string;
    postalCode?: string;
    country?: string;
  };
  lineItems?: Array<{
    name?: string;
    quantity?: number;
    unitAmount?: number;
    partNumber?: string;
    _key: string;
  }>;
  subtotal?: number;
  shipping?: number;
  tax?: number;
  total?: number;
  trackingNumber?: string;
  trackingUrl?: string;
  carrier?: string;
  servicelevel?: string;
  labelUrl?: string;
  shippoRateId?: string;
  shippoTransactionId?: string;
  shippedAt?: string;
  parcel?: {
    length?: number;
    width?: number;
    height?: number;
    weight?: number;
  };
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Banner = {
  _id: string;
  _type: "banner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  subheading?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  ctaText?: string;
  ctaLink?: string;
  discount?: string;
  isActive?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  price?: number;
  compareAtPrice?: number;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  details?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  category?: CategoryReference;
  specifications?: Array<{
    label?: string;
    value?: string;
    _key: string;
  }>;
  partNumber?: string;
  crossReferences?: Array<string>;
  inStock?: boolean;
  featured?: boolean;
  brand?: string;
  productType?: string;
  published?: boolean;
  seoTitle?: string;
  seoDescription?: string;
  vehicleFit?: Array<string>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  order?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Order
  | SanityImageAssetReference
  | Banner
  | SanityImageCrop
  | SanityImageHotspot
  | CategoryReference
  | Product
  | Category
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: allProductsQuery
// Query: *[_type == "product" && published != false && defined(slug.current)] | order(_createdAt desc) {  _id,  name,  slug,  "images": images[0...1],  price,  compareAtPrice,  category->{name, slug},  partNumber,  crossReferences,  vehicleFit,  inStock,  featured,  brand,  productType}
export type AllProductsQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  price: number | null;
  compareAtPrice: number | null;
  category: {
    name: string | null;
    slug: Slug | null;
  } | null;
  partNumber: string | null;
  crossReferences: Array<string> | null;
  vehicleFit: Array<string> | null;
  inStock: boolean | null;
  featured: boolean | null;
  brand: string | null;
  productType: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: productBySlugQuery
// Query: *[_type == "product" && published != false && defined(slug.current) && slug.current == $slug][0] {  _id,  name,  slug,  images,  price,  compareAtPrice,  description,  details,  category->{name, slug},  "categoryId": category._ref,  specifications,  partNumber,  crossReferences,  vehicleFit,  inStock,  featured,  brand,  productType,  seoTitle,  seoDescription}
export type ProductBySlugQueryResult = {
  _id: string;
  name: string | null;
  slug: Slug | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  price: number | null;
  compareAtPrice: number | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  details: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  category: {
    name: string | null;
    slug: Slug | null;
  } | null;
  categoryId: string | null;
  specifications: Array<{
    label?: string;
    value?: string;
    _key: string;
  }> | null;
  partNumber: string | null;
  crossReferences: Array<string> | null;
  vehicleFit: Array<string> | null;
  inStock: boolean | null;
  featured: boolean | null;
  brand: string | null;
  productType: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: featuredProductsQuery
// Query: *[_type == "product" && published != false && defined(slug.current)] | order(featured desc, _createdAt desc) [0...8] {  _id,  name,  slug,  "images": images[0...1],  price,  compareAtPrice,  category->{name, slug},  partNumber,  crossReferences,  vehicleFit,  inStock,  featured,  brand,  productType}
export type FeaturedProductsQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  price: number | null;
  compareAtPrice: number | null;
  category: {
    name: string | null;
    slug: Slug | null;
  } | null;
  partNumber: string | null;
  crossReferences: Array<string> | null;
  vehicleFit: Array<string> | null;
  inStock: boolean | null;
  featured: boolean | null;
  brand: string | null;
  productType: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: relatedProductsQuery
// Query: *[  _type == "product" && published != false && defined(slug.current)  && _id != $productId  && category._ref == $categoryId] | order(_createdAt desc) [0...4] {  _id,  name,  slug,  "images": images[0...1],  price,  compareAtPrice,  category->{name, slug},  partNumber,  crossReferences,  vehicleFit,  inStock,  featured,  brand,  productType}
export type RelatedProductsQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  price: number | null;
  compareAtPrice: number | null;
  category: {
    name: string | null;
    slug: Slug | null;
  } | null;
  partNumber: string | null;
  crossReferences: Array<string> | null;
  vehicleFit: Array<string> | null;
  inStock: boolean | null;
  featured: boolean | null;
  brand: string | null;
  productType: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: allCategoriesQuery
// Query: *[_type == "category"] | order(order asc) {  _id,  name,  slug,  description,  image}
export type AllCategoriesQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  description: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: searchProductsQuery
// Query: *[_type == "product" && published != false && defined(slug.current) && (  partNumber match $term ||  name match $term ||  pt::text(description) match $term ||  $rawTerm in crossReferences ||  count(crossReferences[@ match $term]) > 0)] | order(_createdAt desc) [0...12] {  _id,  name,  slug,  "images": images[0...1],  price,  compareAtPrice,  category->{name, slug},  partNumber,  crossReferences,  inStock}
export type SearchProductsQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  price: number | null;
  compareAtPrice: number | null;
  category: {
    name: string | null;
    slug: Slug | null;
  } | null;
  partNumber: string | null;
  crossReferences: Array<string> | null;
  inStock: boolean | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: productSlugsByIdsQuery
// Query: *[_type == "product" && published != false && defined(slug.current) && _id in $ids] {  _id,  "slug": slug.current}
export type ProductSlugsByIdsQueryResult = Array<{
  _id: string;
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: productSitemapQuery
// Query: *[_type == "product" && published != false && defined(slug.current)] {  slug,  _updatedAt}
export type ProductSitemapQueryResult = Array<{
  slug: Slug | null;
  _updatedAt: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: categorySitemapQuery
// Query: *[_type == "category" && defined(slug.current)] {  slug,  _updatedAt}
export type CategorySitemapQueryResult = Array<{
  slug: Slug | null;
  _updatedAt: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: heroBannerQuery
// Query: *[_type == "banner" && isActive == true][0] {  _id,  heading,  subheading,  image,  ctaText,  ctaLink,  discount}
export type HeroBannerQueryResult = {
  _id: string;
  heading: string | null;
  subheading: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  ctaText: string | null;
  ctaLink: string | null;
  discount: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: shopFacetQuery
// Query: *[_type == "product" && published != false && defined(slug.current)] {  _id,  name,  price,  inStock,  vehicleFit,  "categorySlug": category->slug.current,  "categoryName": category->name}
export type ShopFacetQueryResult = Array<{
  _id: string;
  name: string | null;
  price: number | null;
  inStock: boolean | null;
  vehicleFit: Array<string> | null;
  categorySlug: string | null;
  categoryName: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: allOrdersQuery
// Query: *[_type == "order"] | order(_createdAt desc) [0...100] {  _id,  _createdAt,  stripeSessionId,  status,  customerName,  customerEmail,  customerPhone,  shippingAddress,  lineItems,  subtotal,  shipping,  tax,  total,  trackingNumber,  trackingUrl,  carrier,  servicelevel,  labelUrl,  shippoRateId,  shippoTransactionId,  shippedAt,  parcel}
export type AllOrdersQueryResult = Array<{
  _id: string;
  _createdAt: string;
  stripeSessionId: string | null;
  status: "cancelled" | "paid" | "ready_to_ship" | "shipped" | null;
  customerName: string | null;
  customerEmail: string | null;
  customerPhone: string | null;
  shippingAddress: {
    name?: string;
    line1?: string;
    line2?: string;
    city?: string;
    state?: string;
    postalCode?: string;
    country?: string;
  } | null;
  lineItems: Array<{
    name?: string;
    quantity?: number;
    unitAmount?: number;
    partNumber?: string;
    _key: string;
  }> | null;
  subtotal: number | null;
  shipping: number | null;
  tax: number | null;
  total: number | null;
  trackingNumber: string | null;
  trackingUrl: string | null;
  carrier: string | null;
  servicelevel: string | null;
  labelUrl: string | null;
  shippoRateId: string | null;
  shippoTransactionId: string | null;
  shippedAt: string | null;
  parcel: {
    length?: number;
    width?: number;
    height?: number;
    weight?: number;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: unshippedOrdersQuery
// Query: *[_type == "order" && status in ["paid", "ready_to_ship"]] | order(_createdAt desc) [0...100] {  _id,  _createdAt,  stripeSessionId,  status,  customerName,  customerEmail,  customerPhone,  shippingAddress,  lineItems,  subtotal,  shipping,  tax,  total,  trackingNumber,  trackingUrl,  carrier,  servicelevel,  labelUrl,  shippoRateId,  shippoTransactionId,  shippedAt,  parcel}
export type UnshippedOrdersQueryResult = Array<{
  _id: string;
  _createdAt: string;
  stripeSessionId: string | null;
  status: "cancelled" | "paid" | "ready_to_ship" | "shipped" | null;
  customerName: string | null;
  customerEmail: string | null;
  customerPhone: string | null;
  shippingAddress: {
    name?: string;
    line1?: string;
    line2?: string;
    city?: string;
    state?: string;
    postalCode?: string;
    country?: string;
  } | null;
  lineItems: Array<{
    name?: string;
    quantity?: number;
    unitAmount?: number;
    partNumber?: string;
    _key: string;
  }> | null;
  subtotal: number | null;
  shipping: number | null;
  tax: number | null;
  total: number | null;
  trackingNumber: string | null;
  trackingUrl: string | null;
  carrier: string | null;
  servicelevel: string | null;
  labelUrl: string | null;
  shippoRateId: string | null;
  shippoTransactionId: string | null;
  shippedAt: string | null;
  parcel: {
    length?: number;
    width?: number;
    height?: number;
    weight?: number;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: orderByIdQuery
// Query: *[_type == "order" && _id == $id][0] {  _id,  _createdAt,  stripeSessionId,  status,  customerName,  customerEmail,  customerPhone,  shippingAddress,  lineItems,  subtotal,  shipping,  tax,  total,  trackingNumber,  trackingUrl,  carrier,  servicelevel,  labelUrl,  shippoRateId,  shippoTransactionId,  shippedAt,  parcel}
export type OrderByIdQueryResult = {
  _id: string;
  _createdAt: string;
  stripeSessionId: string | null;
  status: "cancelled" | "paid" | "ready_to_ship" | "shipped" | null;
  customerName: string | null;
  customerEmail: string | null;
  customerPhone: string | null;
  shippingAddress: {
    name?: string;
    line1?: string;
    line2?: string;
    city?: string;
    state?: string;
    postalCode?: string;
    country?: string;
  } | null;
  lineItems: Array<{
    name?: string;
    quantity?: number;
    unitAmount?: number;
    partNumber?: string;
    _key: string;
  }> | null;
  subtotal: number | null;
  shipping: number | null;
  tax: number | null;
  total: number | null;
  trackingNumber: string | null;
  trackingUrl: string | null;
  carrier: string | null;
  servicelevel: string | null;
  labelUrl: string | null;
  shippoRateId: string | null;
  shippoTransactionId: string | null;
  shippedAt: string | null;
  parcel: {
    length?: number;
    width?: number;
    height?: number;
    weight?: number;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: orderByStripeSessionQuery
// Query: *[_type == "order" && stripeSessionId == $sessionId][0] { _id }
export type OrderByStripeSessionQueryResult = {
  _id: string;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "product" && published != false && defined(slug.current)] | order(_createdAt desc) {\n  _id,\n  name,\n  slug,\n  "images": images[0...1],\n  price,\n  compareAtPrice,\n  category->{name, slug},\n  partNumber,\n  crossReferences,\n  vehicleFit,\n  inStock,\n  featured,\n  brand,\n  productType\n}': AllProductsQueryResult;
    '*[_type == "product" && published != false && defined(slug.current) && slug.current == $slug][0] {\n  _id,\n  name,\n  slug,\n  images,\n  price,\n  compareAtPrice,\n  description,\n  details,\n  category->{name, slug},\n  "categoryId": category._ref,\n  specifications,\n  partNumber,\n  crossReferences,\n  vehicleFit,\n  inStock,\n  featured,\n  brand,\n  productType,\n  seoTitle,\n  seoDescription\n}': ProductBySlugQueryResult;
    '*[_type == "product" && published != false && defined(slug.current)] | order(featured desc, _createdAt desc) [0...8] {\n  _id,\n  name,\n  slug,\n  "images": images[0...1],\n  price,\n  compareAtPrice,\n  category->{name, slug},\n  partNumber,\n  crossReferences,\n  vehicleFit,\n  inStock,\n  featured,\n  brand,\n  productType\n}': FeaturedProductsQueryResult;
    '*[\n  _type == "product" && published != false && defined(slug.current)\n  && _id != $productId\n  && category._ref == $categoryId\n] | order(_createdAt desc) [0...4] {\n  _id,\n  name,\n  slug,\n  "images": images[0...1],\n  price,\n  compareAtPrice,\n  category->{name, slug},\n  partNumber,\n  crossReferences,\n  vehicleFit,\n  inStock,\n  featured,\n  brand,\n  productType\n}': RelatedProductsQueryResult;
    '*[_type == "category"] | order(order asc) {\n  _id,\n  name,\n  slug,\n  description,\n  image\n}': AllCategoriesQueryResult;
    '*[_type == "product" && published != false && defined(slug.current) && (\n  partNumber match $term ||\n  name match $term ||\n  pt::text(description) match $term ||\n  $rawTerm in crossReferences ||\n  count(crossReferences[@ match $term]) > 0\n)] | order(_createdAt desc) [0...12] {\n  _id,\n  name,\n  slug,\n  "images": images[0...1],\n  price,\n  compareAtPrice,\n  category->{name, slug},\n  partNumber,\n  crossReferences,\n  inStock\n}': SearchProductsQueryResult;
    '*[_type == "product" && published != false && defined(slug.current) && _id in $ids] {\n  _id,\n  "slug": slug.current\n}': ProductSlugsByIdsQueryResult;
    '*[_type == "product" && published != false && defined(slug.current)] {\n  slug,\n  _updatedAt\n}': ProductSitemapQueryResult;
    '*[_type == "category" && defined(slug.current)] {\n  slug,\n  _updatedAt\n}': CategorySitemapQueryResult;
    '*[_type == "banner" && isActive == true][0] {\n  _id,\n  heading,\n  subheading,\n  image,\n  ctaText,\n  ctaLink,\n  discount\n}': HeroBannerQueryResult;
    '*[_type == "product" && published != false && defined(slug.current)] {\n  _id,\n  name,\n  price,\n  inStock,\n  vehicleFit,\n  "categorySlug": category->slug.current,\n  "categoryName": category->name\n}': ShopFacetQueryResult;
    '*[_type == "order"] | order(_createdAt desc) [0...100] {\n  _id,\n  _createdAt,\n  stripeSessionId,\n  status,\n  customerName,\n  customerEmail,\n  customerPhone,\n  shippingAddress,\n  lineItems,\n  subtotal,\n  shipping,\n  tax,\n  total,\n  trackingNumber,\n  trackingUrl,\n  carrier,\n  servicelevel,\n  labelUrl,\n  shippoRateId,\n  shippoTransactionId,\n  shippedAt,\n  parcel\n}': AllOrdersQueryResult;
    '*[_type == "order" && status in ["paid", "ready_to_ship"]] | order(_createdAt desc) [0...100] {\n  _id,\n  _createdAt,\n  stripeSessionId,\n  status,\n  customerName,\n  customerEmail,\n  customerPhone,\n  shippingAddress,\n  lineItems,\n  subtotal,\n  shipping,\n  tax,\n  total,\n  trackingNumber,\n  trackingUrl,\n  carrier,\n  servicelevel,\n  labelUrl,\n  shippoRateId,\n  shippoTransactionId,\n  shippedAt,\n  parcel\n}': UnshippedOrdersQueryResult;
    '*[_type == "order" && _id == $id][0] {\n  _id,\n  _createdAt,\n  stripeSessionId,\n  status,\n  customerName,\n  customerEmail,\n  customerPhone,\n  shippingAddress,\n  lineItems,\n  subtotal,\n  shipping,\n  tax,\n  total,\n  trackingNumber,\n  trackingUrl,\n  carrier,\n  servicelevel,\n  labelUrl,\n  shippoRateId,\n  shippoTransactionId,\n  shippedAt,\n  parcel\n}': OrderByIdQueryResult;
    '*[_type == "order" && stripeSessionId == $sessionId][0] { _id }': OrderByStripeSessionQueryResult;
  }
}
